name: 'Run textlint with reviewdog'
description: '🐶Run textlint with reviewdog on pull requests to improve document writing experience.'
author: 'Tsuyoshi CHO <Tsuyoshi.CHO+develop@Gmail.com>'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: false
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-check,github-pr-review].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
    required: false
  textlint_flags:
    description: "flags and args of textlint command. Default: '.'"
    default: '.'
    required: false
  textlint_version:
    description: "if textlint do not contain in project, use this version. default:'11.6.3'"
    default: '11.6.3'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'alert-octagon'
  color: 'blue'
